language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script:
  - vendor/bin/tester -c tests/php.ini-unix tests -s
  # php code sniffer
  - vendor/bin/phpcs src --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/code-sniffer-ruleset.xml
  - vendor/bin/phpcs tests/ZenifyTests/DoctrineExtensionsTree --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/code-sniffer-ruleset.xml

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
